### ISSUE TITLE
Dovecot and smtpd.conf key/cert filenames don't match

### ISSUE THREAD

**Issue by tdm4** [gonzalo-/ansible-role-mailserver#2]
https://github.com/gonzalo-/ansible-role-mailserver/blob/68503cfcdb8a70eeae8ea4a09e68e9302930382d/templates/10-ssl.conf.j2#L3

https://github.com/gonzalo-/ansible-role-mailserver/blob/master/templates/smtpd.conf.j2#L7

Lines 2-3 for the SSL key and cert should match what ```/etc/mail/smtpd.conf``` use for key and cert. The dovecot uses underscores, the smtpd.conf uses '.'s.

**Comment by gonzalo-** [comment]
Done!

Thanks!
